<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Shopping cart totals template
 * @var $block \Magento\Checkout\Block\Cart\Totals
 */
?>
<tr>
    <td colspan="6">
        <div class="shopping-cart-footer">
            <div id="cart-totals" class="cart-totals" data-bind="scope:'block-totals'">
                <!-- ko template: getTemplate() --><!-- /ko -->
                <script type="text/x-magento-init">
                        {
                            "#cart-totals": {
                                "Magento_Ui/js/core/app": <?= /* @escapeNotVerified */ $block->getJsLayout() ?>
                            }
                        }
                </script>
            </div>
        </div>
    </td>
</tr>
