<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Newsletter\Block\Subscribe $block */

?>
<div class="cta-form">
    <form class="form subscribe"
        novalidate
        action="<?= $block->escapeUrl($block->getFormActionUrl()) ?>"
        method="post"
        data-mage-init='{"validation": {"errorClass": "mage-error"}}'
        id="newsletter-validate-detail">
        <input name="email" type="email" id="newsletter"
            class="input-text"
            placeholder="<?= $block->escapeHtmlAttr(__('Your email address')) ?>"
            data-validate="{required:true, 'validate-email':true}"/>
        <button class="input-submit fa fa-send"
                title="<?= $block->escapeHtmlAttr(__('Subscribe')) ?>"
                type="submit">
        </button>
    </form>
</div>
