<?php
/**
 * Copyright © 2016 Ihor Vansach (ihor@magefan.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog tag claud sidebar template
 *
 * @var $block \Magefan\Blog\Block\Sidebar\TagClaud
 */
?>

<?php $tags = $this->getTags(); ?>

<?php if (count($tags)) { ?>
<?php $maxCount = $this->getMaxCount() ?>

<div class="widget block block-tagclaud m-t-40" data-bind="scope: 'tagclaud'">
    <div class="tags-widget-1">
        <div class="heading-widget">
            <h3><?php echo __('SEARCH BY TAGS') ?></h3>
        </div>
        <ul class="tags-list">
            <?php foreach ($tags as $tag) { ?>
                <?php $title = $block->escapeHtml($tag->getTitle()) ?>
                    <li>
                        <a href="<?php echo $tag->getTagUrl() ?>" title="<?php echo $title ?>">
                            <?php echo $title ?>
                        </a>
                    </li>
            <?php } ?>
        </ul>
     </div>
</div>
<?php } ?>
<div class="m-t-200"></div>
<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('eco-blog-post-slidebar')->toHtml();?>
<div class="m-b-50"></div>
