<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * Product media data template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Gallery
 */
?>
<?php
    /* @escapeNotVerified */ $json=$block->getGalleryImagesJson();
    $array = json_decode($json,true);
    array_shift($array);
?>
<div class="m-b-15">
    <!-- .product-detail-image-1-->
    <div class="product-detail-image-1">
        <div class="product-primary-image owl-carousel" data-carousel-items="1" data-carousel-dotsData="true" data-carousel-nav="true" data-carousel-dots="true" data-carousel-xs="1" data-carousel-sm="1" data-carousel-md="1" data-carousel-lg="1" data-carousel-animateout="fadeOut"
             data-carousel-animatein="fadeIn">
            <?php foreach($array as $item): ?>
                <img data-dot="&lt;img src='<?php echo  $item['full'] ?>'&gt;" src="<?php echo  $item['full'] ?>" alt="product detail image" />
            <?php endforeach; ?>
        </div>
    </div>
    <!-- end .product-detail-image-1-->
</div>

