<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/** @var \Magento\Wishlist\Block\Customer\Wishlist\Items $block */
$columns = $block->getColumns();
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$abstractProductBlock = $block->getLayout()->createBlock('\Magento\Catalog\Block\Product\AbstractProduct');
$wishlistHelper = $this->helper('Magento\Wishlist\Helper\Data');
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$listBlock = $objectManager->get('\Magento\Catalog\Block\Product\ListProduct');

?>

<div class="page-content p-t-40 p-b-90">
    <?php if (count($block->getItems())): ?>
    <div class="container">
        <div class="shopping-cart-1">
            <table class="shop_table shop_table_responsive cart woocommerce-cart-form__contents shopping-cart-content table-bordered">
                <thead>
                <tr>
                    <th class="product-thumbnail">PRODUCT</th>
                    <th class="product-name">NAME & DESCRIPTION</th>
                    <th class="product-price">PRICE</th>
                    <th class="product-status">PRODUCT STATUS</th>
                    <th class="product-atc">ADD TO CART</th>
                    <th class="product-remove"></th>
                </tr>
                </thead>
                <tbody>
                    <?php foreach ($block->getItems() as $item): ?>
                        <?php $product = $item->getProduct();?>
                        <tr data-row="product-item" class="product-item cart_item shopping-cart-item" id="item_<?= $block->escapeHtmlAttr($item->getId()) ?>">
                            <td class="product-thumbnail">
                                <a href="<?php /* @escapeNotVerified */ echo $product->getProductUrl(); ?>" title="<?= $block->escapeHtmlAttr($product->getName()) ?>">
                                    <img class="attachment-shop_thumbnail size-shop_thumbnail wp-post-image" width="90" src="<?php echo $block->getUrl('pub/media/catalog').'product'.$product->getImage();?>" />
                                </a>
                            </td>
                            <td class="product-name" data-title="Product">
                                <a href="<?php /* @escapeNotVerified */echo $product->getProductUrl();  ?>" title="<?= $block->escapeHtmlAttr($product->getName()) ?>"
                                   class="product-item-link"><?= $block->escapeHtml($product->getName()) ?>
                                </a>
                            </td>
                            <td class="product-price" data-title="Price">
                                <?php echo $abstractProductBlock->getProductPrice($product) ?>
                            </td>
                            <td class="product-status">
                                <?php if ($product->getIsSalable()): ?>
                                    <span><?= $block->escapeHtml(__('In stock')) ?></span>
                                <?php else: ?>
                                    <span><?= $block->escapeHtml(__('Out of stock')) ?></span>
                                <?php endif; ?>
                            </td>
                            <td class="product-atc">
                                <?php if ($product->isSaleable()): ?>
                                    <?php if ($product->getTypeInstance()->hasRequiredOptions($product)): ?>
                                        <a href="#" data-mage-init='{"redirectUrl":{"url":"<?php /* @escapeNotVerified */ echo $block->getAddToCartUrl($product) ?>"}}'
                                           data-toggle-tooltip="tooltip" data-placement="top"
                                           title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                           <?php echo __('Add to Cart')?>
                                        </a>
                                    <?php else: ?>
                                        <?php
                                        $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                        $postData = $postDataHelper->getPostData($block->getAddToCartUrl($product), ['product' => $product->getEntityId()])
                                        ?>
                                        <a href="#" data-post='<?php /* @escapeNotVerified */ echo $postData; ?>'
                                           data-toggle-tooltip="tooltip" data-placement="top"
                                           title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                           <?php echo __('Add to Cart')?>
                                        </a>
                                    <?php endif; ?>
                                <?php endif ?>
                            </td>
                            <td class="product-remove">
                                <a href="#" data-role="remove" data-post='<?= $wishlistHelper->getRemoveParams($item) ?>'
                                   title="<?= $block->escapeHtmlAttr(__('Remove Item')) ?>" class="remove fa fa-close">
                                </a>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    <?php else: ?>
        <div class="message info empty">
            <span><?= $block->escapeHtml(__('This Wish List has no Items')) ?></span>
        </div>
    <?php endif; ?>
    </div>
</div>
