<div class="footer-fond-haut"></div>
<div class="footer-fond">
    <div class="footer-container">
        <div class="footer-mailing-list">
            <div class="footer-mailing-list-text">STAY UPDATED<span class="text-yellow">Get Specials, Exclusive Promotions & News</span></div>
            <form class="footer-mailing-list-form">
                <label class="sr-only" for="exampleInputEmail3">Email address</label>
                <input type="email" class="footer-mailing-input" id="exampleInputEmail4" placeholder="Your email address here">
                <button type="submit" class="footer-suscribe-btn">SUSCRIBE</button>
            </form>
        </div>
        <div class="footer-sep"></div>
        <div class="footer-row-4-column">
            <div class="footer-col footer-col-1">
                <div class="footer-col-title">ABOUT US</div>
                <div class="footer-col-content">
                     <p class="footer-p-style-1">For Essiac® product information and the manufacturer's suggested protocols please call us</p>
                     <p class="footer-infos-tel">TOLL FREE USA/Canada <span class="green-text">1-888-900-2299</span></p>
                     <p class="footer-infos-tel hidden">INTERNATIONAL <span class="green-text">1-514-695-2299</span></p>
                     <p>-EST between 8 a.m. and 8 p.m.-</p>  
                </div>
            </div>
            <div class="footer-col footer-col-2">
                <div class="footer-col-title">Information</div>
                <div class="footer-col-content">
                    <ul class="footer-menu">
                        <li><a href="<?php echo $block->getBaseUrl(); ?>essiac-products">ESSIAC <span class="weight-400">PRODUCTS</span></a></li>
                        <li><a href="<?php echo $block->getBaseUrl(); ?>tru-pine-products">TRU-PINE <span class="weight-400">PRODUCTS</span></a></li>
                        <li><a href="<?php echo $block->getBaseUrl(); ?>pet-products">PET <span class="weight-400">PRODUCTS</span></a></li>
                        <li><a href="<?php echo $block->getBaseUrl(); ?>naka-products">NAKA <span class="weight-400">PRODUCTS</span></a></li>
                        <li><a href="<?php echo $block->getBaseUrl(); ?>hubner-products">HUBNER <span class="weight-400">PRODUCTS</span></a></li>
                        <li><a href="<?php echo $block->getBaseUrl(); ?>contact-us">CONTACT</a></li>
                        <li><a href="#">Blog</a></li>
                    </ul>
                </div>
            </div>
            <div class="footer-col footer-col-3">
                <div class="footer-col-title">My account</div>
                <div class="footer-col-content">
                    <ul class="footer-menu">
                        <li><a href="<?php echo $block->getUrl('customer/account', ['_secure' => true]);?>">My account</a></li>
                        <li><a href="<?php echo $block->getUrl('customer/account', ['_secure' => true]);?>">Log in</a></li>
                        <li><a href="<?php echo $block->getUrl('checkout/cart', ['_secure' => true]);?>">My cart</a></li>
                        <li><a href="<?php echo $block->getBaseUrl(); ?>altramed-rewards-program">Altramed Rewards program</a></li>
                    </ul>
                </div>
            </div>
            <div class="footer-col footer-col-4">
                <div class="footer-col-title">Essiac® Corporate Profile</div>
                <div class="footer-col-content">
                    <ul class="footer-menu">
		                <li><a href="<?php echo $block->getBaseUrl(); ?>canadian-success-story-en">Canadian Success story</a></li>
		                <li><a href="<?php echo $block->getBaseUrl(); ?>ccnm-new-release-en">CCNM New Release</a></li>
		                <li><a href="<?php echo $block->getBaseUrl(); ?>caisse-memorial-theater">Caisse Memorial Theater</a></li>
		                <li><a href="<?php echo $block->getBaseUrl(); ?>distributor-inquiries-welcomed-en">Distributor Inquiries Welcomed</a></li>
                    </ul>
                    <ul class="footer-menu-2">
                        <li>
                           GENERAL INFORMATION
                            <ul class="footer-sous-menu-2">
                                <li><a href="<?php echo $block->getBaseUrl(); ?>ask-a-question">Ask Us A Product Question</a></li>
                                <li><a href="<?php echo $block->getBaseUrl(); ?>privacy-policy">Privacy Policy</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="footer-sep"></div>
        <div class="footer-text-infos"><p class="border">* These statements have not been evaluated by the Food and Drug Administration. This product is not intended to diagnose, treat, cure, or prevent any disease.</p><p>Web site owners shall require written permission from Altramed H P. Inc. before creating second part internet links to their sites. This is to insure that Altramed H P. Inc. is not connected to other web sites that are in violation with the Canadian Health Protection Board of Canada and/or the United States FDA. Web sites refusing to remove links when asked to do so, may be subject to legal action. Copyright © 2008 Altram </p>  
        </div>
        <div class="footer-sep"></div>
    </div>
</div>