<?php
/**
 * Copyright © 2015 Ihor Vansach (ihor@magefan.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog related posts template
 *
 * @var $block \Magefan\Blog\Block\Post\View\RelatedPosts
 */
?>

<?php if ($block->displayPosts()) { ?>
    <?php $_postCollection = $block->getPostCollection(); ?>
    <?php if ($_postCollection->count()) { ?>
    <div class="other-post-1">
        <h4 class="title"><?php echo __('Other Post:') ?> </h4>
        <div class="row">
            <?php foreach ($_postCollection as $_post) { ?>
            <div class="col-md-6">
            <!-- .blog-item-1-->
                <div class="blog-item-1">
                    <div class="blog-item-image">
                        <a href="<?php echo $_post->getPostUrl() ?>">
                            <img src="<?php echo $_post->getFeaturedImage() ?>" />
                        </a>
                    </div>
                    <div class="blog-item-title">
                        <h3 class="title">
                            <a href="<?php echo $_post->getPostUrl() ?>">
                                <?php echo $block->escapeHtml($_post->getTitle()); ?>
                            </a>
                        </h3>
                    </div>
                    <p class="blog-item-date">
                        <i class="fa fa-clock-o"></i>
                        <span><?php echo date_format(new DateTime($_post->getPublishDate()),"F d, Y"); ?></span>
                    </p>
                </div>
            </div>
            <?php } ?>
        </div>
    </div>
    <?php } ?>
<?php } ?>