<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Template for filter items block
 *
 * @var $block \Magento\LayeredNavigation\Block\Navigation\FilterRenderer
 */
?>
<?php


?>
<?php if($filter instanceof Magento\CatalogSearch\Model\Layer\Filter\Price ):?>
<?php $range =  $this->getPriceRange($filter);?>
<?php $url = $this->getFilterUrl($filter);?>
<?php //var_dump($url);?>
<script>
var price_url = "<?=$url;?>";
require([
    'jquery',
    "jquery/ui",
    'domReady!'
], function($){
    $("div#price-slider").slider({
			range: true,
			min: <?=$range['min']?>,
			max: <?=$range['max']?>,
			values: [ <?=$range['min']?>, <?=$range['max']?> ],
			slide: function( event, ui ) {
				$( "#amount" ).val( "$" + ui.values[ 0 ] + " - $" + ui.values[ 1 ] );
			},
			change: function( event, ui ) {
				var filter_url = price_url+ui.values[0]+"-"+ui.values[1];
                $(".filter-url-price").attr("href", filter_url);
			}
		});
		$( "#amount" ).val( "$" + $( "#price-slider" ).slider( "values", 0 ) +
			" - $" + $( "#price-slider" ).slider( "values", 1 ) );
});
</script>
<?php 
?>
<div class="filter-content filter-by-price-widget-1">
    <div id="price-slider" class="filter-bar"></div>
    <div class="filter-action">
        <span class="price">Price: </span><input type="text" id="amount" readonly style="border:0; color:##666; font-weight:400; font-family: 'Montserrat', Arial, 'Helvetica Neue', sans-serif; font-size: 14px; width: 40% ">
        <a class="filter-url-price" href="javascript:void(0)">
            <button class="au-btn au-btn-radius btn-filter">FILTER</button>
        </a>
    </div>
</div>
<?php else:?>
<ol class="items">
    <?php foreach ($filterItems as $filterItem): ?>
        <li class="my item">
            <?php if ($filterItem->getCount() > 0): ?>
                <a href="<?php echo $block->escapeUrl($filterItem->getUrl()) ?>">
                    <?php /* @escapeNotVerified */ echo $filterItem->getLabel() ?>
                    <?php if ($this->helper('\Magento\Catalog\Helper\Data')->shouldDisplayProductCountOnLayer()): ?>
                        <span class="count"><?php /* @escapeNotVerified */ echo $filterItem->getCount()?><span class="filter-count-label">
                            <?php if ($filterItem->getCount() == 1):?> <?php /* @escapeNotVerified */ echo __('item')?><?php else:?> <?php /* @escapeNotVerified */ echo __('items') ?><?php endif;?></span></span>
                    <?php endif; ?>
                </a>
            <?php else:?>
                <?php /* @escapeNotVerified */ echo $filterItem->getLabel() ?>
                <?php if ($this->helper('\Magento\Catalog\Helper\Data')->shouldDisplayProductCountOnLayer()): ?>
                    <span class="count"><?php /* @escapeNotVerified */ echo $filterItem->getCount()?><span class="filter-count-label">
                        <?php if ($filterItem->getCount() == 1):?><?php /* @escapeNotVerified */ echo __('item')?><?php else:?><?php /* @escapeNotVerified */ echo __('items') ?><?php endif;?></span></span>
                <?php endif; ?>
            <?php endif; ?>
        </li>
    <?php endforeach ?>
</ol>
<?php endif;?>
