<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?php /* @escapeNotVerified */ echo __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
    <?php echo $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $image = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="page-content p-t-40 p-b-70 <?php /* @escapeNotVerified */ echo $viewMode; ?> products-<?php /* @escapeNotVerified */ echo $viewMode; ?>">
        <?php $iterator = 1; ?>
        <div class="toolbar-top">
            <?php echo $block->getToolbarHtml() ?>
        </div>
        <ol class="products list items product-items row">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
                <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="col-md-4 col-sm-6">' : '</li><li class="col-md-4 col-sm-6">' ?>
                <div class="product-item-info product-1" data-container="product-grid">
                    <div class="product-image">
                        <?php
                        $productImage = $block->getImage($_product, $image);
                        if ($pos != null) {
                            $position = ' style="left:' . $productImage->getWidth() . 'px;'
                                . 'top:' . $productImage->getHeight() . 'px;"';
                        }
                        ?>
                        <?php // Product Image ?>
                        <div class="image-holder">
                            <img src="<?php echo $block->getUrl('pub/media/catalog').'product'.$_product->getImage();?>" />
                        </div>


                        <div class="product-action">
                            <div class="product-action-list">
                                <div class="action-item">
                                    <a class="fa fa-search-plus" href="#"
                                       data-toggle="modal"
                                       data-target="#myModal-list-<?php echo $_product->getId();?>"
                                       data-toggle-tooltip="tooltip"
                                       data-placement="top" title="Quick view">
                                    </a>
                                </div>
                                <div class="action-item">
                                    <?php if ($_product->isSaleable()): ?>
                                        <?php if ($_product->getTypeInstance()->hasRequiredOptions($_product)): ?>
                                            <a class="fa fa-shopping-cart" href="#"
                                               data-mage-init='{"redirectUrl":{"url":"<?php /* @escapeNotVerified */ echo $block->getAddToCartUrl($_product) ?>"}}'
                                               data-toggle-tooltip="tooltip" data-placement="top"
                                               title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                            </a>
                                        <?php else: ?>
                                            <?php
                                            $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                            $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_product), ['product' => $_product->getEntityId()])
                                            ?>
                                            <a class="fa fa-shopping-cart" href="#"
                                               data-post='<?php /* @escapeNotVerified */ echo $postData; ?>'
                                               data-toggle-tooltip="tooltip" data-placement="top"
                                               title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                            </a>
                                        <?php endif; ?>
                                    <?php else: ?>
                                        <?php if ($_product->getIsSalable()): ?>
                                            <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                        <?php else: ?>
                                            <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </div>
                                <div class="action-item">
                                    <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
                                        <a href="#"
                                           data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>'
                                           class="fa fa-heart" data-action="add-to-wishlist"
                                           data-toggle-tooltip="tooltip" data-placement="top"
                                           title="<?php /* @escapeNotVerified */ echo __('Add to Wish List') ?>">
                                        </a>
                                    <?php endif; ?>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="product-content">
                        <?php
                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                        ?>
                        <h3 class="title">
                            <a class="name"
                               href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
                                <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                            </a>
                        </h3>
                        <?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>
                        <?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
                        <?php echo $block->getProductDetailsHtml($_product); ?>

                         <?php if ($showDescription):?>
                            <div class="product description product-item-description">
                                <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" title="<?php /* @escapeNotVerified */ echo $_productNameStripped ?>"
                                   class="action more"><?php /* @escapeNotVerified */ echo __('Learn More') ?></a>
                            </div>
                         <?php endif; ?>
                    </div>
                </div>
                <!-- quick-view-1-->
                <div class="modal fade quick-view-1" id="myModal-list-<?php echo $_product->getId();?>" role="dialog">
                    <div class="modal-dialog">
                        <!-- Modal content-->
                        <div class="modal-content">
                            <div class="modal-header">
                                <button class="fa fa-close" type="button" data-dismiss="modal"></button>
                            </div>
                            <div class="modal-body">
                                <div class="row">
                                    <div class="col-md-5">
                                        <!-- .product-detail-image-1-->
                                        <div class="product-detail-image-1">
                                            <img src="<?php echo $block->getUrl('pub/media/catalog').'product'.$_product->getImage();?>" />
                                        </div>
                                        <!-- end .product-detail-image-1-->
                                    </div>

                                    <div class="col-md-7">
                                        <!-- .product-detail-content-1-->
                                        <div class="product-detail-content-1">
                                            <div class="product-name">
                                                <h3><?php echo $_product->getName() ?></h3>
                                            </div>
                                            <div class="product-cert"></div>
                                            <div class="product-price">
                                                <?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
                                            </div>
                                            <div class="product-introduce">
                                                <p><?php echo $_product->getShortDescription(); ?></p>
                                                <?php if ($_product->getIsSalable()): ?>
                                                    <p><?php /* @escapeNotVerified */ echo __('In stock') ?></p>
                                                <?php else: ?>
                                                    <p><?php /* @escapeNotVerified */ echo __('Out of stock') ?></p>
                                                <?php endif; ?>
                                                <p>SKU: <?php echo $_product->getSku(); ?></p>
                                            </div>

                                            <!-- .product-form add to cart-->
                                            <div class="prodcut-add-to-cart">
                                                <form action="<?= /* @escapeNotVerified */ $block->getSubmitUrl($_product) ?>" method="post"
                                                      id="product_addtocart_form_<?php echo $_product->getId();?>" enctype="multipart/form-data">
                                                    <input type="hidden" name="product" value="<?= /* @escapeNotVerified */ $_product->getId() ?>" />
                                                    <input type="hidden" name="selected_configurable_option" value="" />
                                                    <input type="hidden" name="related_product" id="related-products-field-<?php echo $_product->getId();?>" value="" />
                                                    <?= $block->getBlockHtml('formkey') ?>
                                                    <?php if (!$block->hasOptions()):?>
                                                        <input type="number"
                                                               name="qty"
                                                               id="qty_<?php echo $_product->getId();?>"
                                                               value="<?= /* @escapeNotVerified */ __('1') ?>"
                                                               title="<?= /* @escapeNotVerified */ __('Qty') ?>"
                                                               class="input-text input-size qty"
                                                               min="1"
                                                        />
                                                        <button class="au-btn au-btn-primary au-btn-radius btn-add-to-cart" type="submit"><?php echo __('ADD TO CART') ?></button>
                                                        <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
                                                            <a class="au-btn au-btn-border au-btn-radius btn-add-to-wishlist" href="#"
                                                               data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>'>
                                                                <?php echo __('ADD TO WISHLIST'); ?>
                                                            </a>
                                                        <?php endif;?>
                                                    <?php else:?>
                                                        <a title="<?php echo $_product->getName() ?>"
                                                           href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>"
                                                           class="product-item-link">
                                                            <?php echo __('Go to detail'); ?>
                                                        </a>
                                                    <?php endif; ?>
                                                </form>
                                            </div>
                                            <!-- end .product-form add to cart-->

                                        </div>
                                        <!-- end .product-detail-content-1-->
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- end quick-view-1-->

                <?php echo($iterator == count($_productCollection)+1) ? '</li>' : '' ?>
            <?php endforeach; ?>
        </ol>
        <div class="toolbar-bottom">
            <?php echo $block->getToolbarHtml() ?>
        </div>
    </div>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>
