<div>
    <h1> Sample Two Test </h1>
    <p>
        <?php
        /* Using magic getsetters */
        echo $this->getSampleText();
        ?>
    </p>
    <p>
        <strong>
            <?php
            /* retrieving sample cfg value */
            echo $this->getCfgSample();
            ?>
        </strong>
		
		<a href="<?php echo $url = $this->getUrl('AdminSample/downloadCSV/index'); ?>">Link</a>
    </p>
</div>
