<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2018 Amasty (https://www.amasty.com)
 * @package Amasty_Orderarchive
 */
?>
<div class="pp-buttons-container">
    <p>
        <button class="primary" id="<?php echo $block->getHtmlId() ?>" onclick="setLocation('<?php echo $block->getAjaxArchivingUrl() ?>')" type="button">
            <?php echo __('Archiving') ?>
        </button>
    </p>
</div>