<?php
/**
 * Copyright © 2015 Ihor Vansach (ihor@magefan.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog post view template
 *
 * @var $block \Magefan\Blog\Block\Post\View
 */
?>
<?php
    $_post = $this->getPost();
    $_postUrl = $_post->getPostUrl();
    $_postName = $block->escapeHtml($_post->getTitle(), null, true);
?>
<div class="post-view m-t-20">
    <div class="post-holder blog-post-1 post-holder-<?php echo $_post->getId() ?>">
        <?php if ($featuredImage = $_post->getFeaturedImage()) { ?>
            <div class="blog-post-cover">
                <img src="<?php echo $featuredImage ?>" alt="<?php echo $_postName ?>" />
            </div>
        <?php } ?>
        <div class="blog-post-title">
            <h3> <?php echo $_postName ?></h3>
        </div>
        <div class="blog-post-date">
            <p>
                <i class="fa fa-clock-o"></i>
                <span><?php echo date_format(new DateTime($_post->getPublishDate()),"F d, Y"); ?></span>
            </p>
        </div>

        <div class="blog-post-content">
            <?php echo $block->getContent() ?>
            <div class="clear"></div>
        </div>

        <?php if ($_post->getTagsCount()) {  ?>
            <ul class="blog-post-tags">
                <?php foreach ($_post->getRelatedTags() as $tag) { ?>
                    <?php $title = $tag->getTitle() ?>
                        <li>
                            <a href="<?php echo $tag->getTagUrl() ?>" title="<?php echo $title ?>">
                                <?php echo $title ?>
                            </a>
                        </li>
                <?php } ?>
            </ul>
        <?php } ?>

        <div class="post-bottom">
            <?php echo $this->getChildHtml('blog.post.bottom') ?>
        </div>
    </div>
</div>