<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<?php
$html = '';
?>
<div class="header-login">
    <ul class="list-top-link-account">
        <li class="icon-account-header">
            <span class="icon-account"><i class="fa fa-user"></i></span>
        </li>
        <?php
        foreach ($this->getLinks() as $link) {
            $html .= $this->renderLink($link);
        }
        echo $html;
        ?>
    </ul>
</div>




