<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div class="copyright">
	<div class="page-main footer-1 footer-last">
	    <div class="pull-left footer-bottom"><span><?php /* @escapeNotVerified */ echo $block->getCopyright() ?></span></div>
	    <div class="pull-right hidden-xs footer-bottom"><?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('eco-footer-social')->toHtml();?></div>
    </div>
</div>

<div id="up-to-top">
    <i class="fa fa-angle-up"></i>
</div>

<script type="text/javascript">
    require([
        'jquery'
    ],function(){
        jQuery(document).ready(function($) {
            if(jQuery("#up-to-top").length > 0) {
                jQuery(document).ready(function(){
                    jQuery(window).scroll(function(){
                        if (jQuery(this).scrollTop() > 100) {
                            jQuery('#up-to-top').fadeIn();
                        } else {
                            jQuery('#up-to-top').fadeOut();
                        }
                    });
                    jQuery('#up-to-top').click(function(){
                        jQuery("html, body").animate({ scrollTop: 0 }, 600);
                        return false;
                    });
                });
            }
        });
    });
</script>


