<a href="/" class="header-logo"><img src="<?php echo $block->getViewFileUrl('images/logo-flawless.png') ?>" class="img-fluid" alt="Logo Flawless" /></a>
<div class="header-description">The new <span class="color-2">GOLD</span> standard in Facial Hair Removal</div>
<div class="header-button-account-cart">
    <!-- <a href="" class="header-button">
        <div class="header-button-text">Order now</div>
    </a> -->
		<?php
		$om = \Magento\Framework\App\ObjectManager::getInstance();
		$productHelper = $om->get('\Magento\Catalog\Model\Product');
		$listBlock = $om->get('\Magento\Catalog\Block\Product\ListProduct');
		?>
		    <a href="" class="header-button">
		        <!-- <div class="order-button-text">Order online</div> -->
						<form  data-role="tocart-form" action="<?php echo $listBlock->getAddToCartUrl($productHelper->load(7));
						?>" method="post">      
						<?php echo $block->getBlockHtml('formkey'); ?>
						    <div class="qty-info" style="display:none;">
						        <span class="add-qty button-qty">+</span>
						        <span class="remove-qty button-qty">-</span>
						        <input class="qty-product3d" oninput="this.value=this.value.replace(/[^0-9]/g,'');" type="hidden" value="1">
						    </div>
						        <button style="margin:0 auto;" class="action tocart primary order-button"
						    type="submit" title="<?php /* @escapeNotVerified */ echo __('Order online') ?>">
						        <span class="header-button-text" style="display: inline-block;"><?php /* @escapeNotVerified */ echo __('Order online') ?></span>
						    </button>
						</form>
		    </a>
		
    <div class="header-account-cart">
        <!-- <a href="" class="header-cart"></a> -->
		<div class="header-registrer">
			<a class="header-account" href="<?php echo $block->getUrl('customer/account', ['_secure' => true]);?>"></a>
		</div>
			<?php echo $this->getChildHtml('minicart') ?>
        </div>
    </div>
</div>
	<script type="text/javascript" charset="utf-8">
		
						//
			// require(['jquery', 'Swiper'], function($){ $(document).ready(function() {
			// 	            // SLIDER CUSTOMER REVIEWS
			// 	            var swiper = new Swiper('.customer-reviews-swiper', {
			// 	              slidesPerView: 2,
			// 	              spaceBetween: 0,
			// 	              slidesPerGroup: 2,
			// 	              loop: true,
			// 	              loopFillGroupWithBlank: true,
			// 	              navigation: {
			// 	                nextEl: '.swiper-button-next',
			// 	                prevEl: '.swiper-button-prev',
			// 	              },
			// 	              breakpoints: {
			// 	                768: {
			// 	                  slidesPerView: 1,
			// 	                  slidesPerGroup: 1,
			// 	                }
			// 	              }
			// 	            });
			// 	            // SLIDER OTHER PRODUCTS
			// 	            var swiper = new Swiper('.other-products-swiper', {
			// 	              slidesPerView: 4,
			// 	              spaceBetween: 30,
			// 	              loop: true,
			// 	              loopFillGroupWithBlank: true,
			// 	              freeMode: true,
			// 	              navigation: {
			// 	                nextEl: '.swiper-2-button-next',
			// 	                prevEl: '.swiper-2-button-prev',
			// 	              },
			// 	              breakpoints: {
			// 	                1400: {
			// 	                  slidesPerView: 3,
			// 	                },
			// 	                  992: {
			// 	                  slidesPerView: 2,
			// 	                },
			// 	                768: {
			// 	                  slidesPerView: 1,
			// 	                }
			// 	              }
			// 	            });
			// });});
	</script>