<?php
/**
 * Copyright © 2015 Ihor Vansach (ihor@magefan.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog post list item template
 *
 * @var $block \Magefan\Blog\Block\Post\AbstractPost
 */
?>
<?php
    $_post = $this->getPost();
    $_postUrl = $_post->getPostUrl();
    $_postName = $block->escapeHtml($_post->getTitle(), null, true);
?>

<div class="col-md-6">
    <!-- .blog-item-1-->
    <div class="blog-item-1">
        <?php if ($featuredImage = $_post->getFeaturedImage()) { ?>
            <div class="blog-item-image">
                <a href="<?php echo $_postUrl ?>" title="<?php echo $_postName ?>">
                    <img src="<?php echo $featuredImage ?>" alt="<?php echo $_postName ?>" />
                </a>
            </div>
        <?php } ?>
        <div class="blog-item-title">
            <h3 class="title">
                <a href="<?php echo $_postUrl ?>" title="<?php echo $_postName ?>">
                    <?php echo $_postName ?>
                </a>
            </h3>
        </div>
        <p class="blog-item-date">
            <i class="fa fa-clock-o"></i>
            <span><?php echo date_format(new DateTime($_post->getPublishDate()),"F d, Y"); ?></span>
        </p>
    </div>
    <!-- end .blog-item-1-->
</div>